// user
export const START_CREATE_USER = 'START_CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

//article
export const START_FETCH_ARTICLE_LIST = 'START_FETCH_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST_SUCCESS = 'FETCH_ARTICLE_LIST_SUCCESS';
export const FETCH_ARTICLE_LIST_FAIL = 'FETCH_ARTICLE_LIST_FAIL';
export const START_FETCH_ARTICLE = 'START_FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';
